export const careers = [
  { label: "Ingeniería de Sistemas", value: "Ingeniería de Sistemas" },
  { label: "Ingeniería Industrial", value: "Ingeniería Industrial" },
  { label: "Ingeniería Electrónica", value: "Ingeniería Electrónica" },
  { label: "Ingeniería de Telecomunicaciones", value: "Ingeniería de Telecomunicaciones" },
  { label: "Ingeniería Biomédica", value: "Ingeniería Biomédica" },
  { label: "Ingeniería Ambiental", value: "Ingeniería Ambiental" },
  { label: "Ingeniería Mecánica", value: "Ingeniería Mecánica" },
  { label: "Ingeniería Civil", value: "Ingeniería Civil" },
  { label: "Ingeniería Mecatrónica", value: "Ingeniería Mecatrónica" },
  { label: "Ingeniería Química", value: "Ingeniería Química" },
  { label: "Ciencias de la Computación", value: "Ciencias de la Computación" },
  { label: "Ciencia de Datos", value: "Ciencia de Datos" },
  { label: "Bioingeniería", value: "Bioingeniería" },
  { label: "Biología", value: "Biología" },
  { label: "Biotecnología", value: "Biotecnología" },
  { label: "Química", value: "Química" },
  { label: "Física", value: "Física" },
  { label: "Matemática", value: "Matemática" },
  { label: "Estadística", value: "Estadística" },
  { label: "Medicina", value: "Medicina" },
  { label: "Enfermería", value: "Enfermería" },
  { label: "Odontología", value: "Odontología" },
  { label: "Tecnología Médica", value: "Tecnología Médica" },
  { label: "Genética", value: "Genética" },
  { label: "Farmacia y Bioquímica", value: "Farmacia y Bioquímica" },
  { label: "Veterinaria", value: "Veterinaria" },
  { label: "Nutrición", value: "Nutrición" },
  { label: "Ecología", value: "Ecología" },
  { label: "Ingeniería Geológica", value: "Ingeniería Geológica" },
  { label: "Ingeniería de Minas", value: "Ingeniería de Minas" },
  { label: "Geofísica", value: "Geofísica" },
  { label: "Geografía", value: "Geografía" },
  { label: "Ingeniería Agronómica", value: "Ingeniería Agronómica" },
  { label: "Agronomía", value: "Agronomía" },
  { label: "Ciencias Agropecuarias", value: "Ciencias Agropecuarias" },
  { label: "Meteorología", value: "Meteorología" },
  { label: "Ingeniería Forestal", value: "Ingeniería Forestal" },
  { label: "Ingeniería Textil", value: "Ingeniería Textil" },
  { label: "Ingeniería de Alimentos", value: "Ingeniería de Alimentos" },
  { label: "Ingeniería Naval", value: "Ingeniería Naval" },
  { label: "Ingeniería Aeronáutica", value: "Ingeniería Aeronáutica" },
  { label: "Ingeniería Espacial", value: "Ingeniería Espacial" },
  { label: "Neurociencia", value: "Neurociencia" },
  { label: "Biofísica", value: "Biofísica" },
  { label: "Nanotecnología", value: "Nanotecnología" },
  { label: "Ingeniería Energética", value: "Ingeniería Energética" },
  { label: "Ingeniería en Inteligencia Artificial", value: "Ingeniería en Inteligencia Artificial" },
  { label: "Robótica", value: "Robótica" },
  { label: "Ingeniería en Software", value: "Ingeniería en Software" }
];