export const challenges = [
    {
      nombre: 'Haz match y agenda una mentoría',
      categoria: 'Conexión',
      objetivo: 'Fomentar nuevas relaciones dentro de la comunidad.',
      tarea: 'Conecta con alguien afín y agenda una mentoría virtual.',
      validacion: 'Captura del chat o formulario',
      puntos: 25,
    },
    {
      nombre: 'Comparte un recurso educativo',
      categoria: 'Exploración',
      objetivo: 'Ayudar a descubrir nuevas herramientas o cursos útiles.',
      tarea: 'Publica una recomendación educativa en la comunidad.',
      validacion: 'Texto validado por formulario o staff',
      puntos: 20,
    },
    {
      nombre: 'Comparte tu motivación',
      categoria: 'Comunidad',
      objetivo: 'Inspirar a otras con tu historia académica.',
      tarea: 'Escribe en comunidad por qué estudias lo que estudias.',
      validacion: 'Publicación validada',
      puntos: 20,
    },
    {
      nombre: 'Propón un mini-proyecto',
      categoria: 'Idea',
      objetivo: 'Iniciar ideas de impacto desde la comunidad.',
      tarea: 'Sube una propuesta de solución a un problema real.',
      validacion: 'Formulario o post validado',
      puntos: 30,
    },
    {
      nombre: 'Mi mayor reto académico',
      categoria: 'Reflexión',
      objetivo: 'Compartir aprendizajes de experiencias personales.',
      tarea: 'Describe el reto más difícil que enfrentaste y cómo lo superaste.',
      validacion: 'Texto validado por el equipo',
      puntos: 20,
    },
    {
      nombre: 'Asiste al taller del mes',
      categoria: 'Acción',
      objetivo: 'Motivar asistencia a eventos educativos.',
      tarea: 'Participa del taller y registra tu código de evento.',
      validacion: 'Código de taller o validación automática',
      puntos: 30,
    },
    {
      nombre: 'Mujeres que inspiran',
      categoria: 'Inspiración',
      objetivo: 'Visibilizar referentes positivos.',
      tarea: 'Comparte una historia o perfil de mujer que te inspire.',
      validacion: 'Publicación validada',
      puntos: 25,
    },
    {
      nombre: 'Arma un equipo',
      categoria: 'Colaboración',
      objetivo: 'Fomentar el trabajo en equipo y liderazgo.',
      tarea: 'Júntate con 2 chicas más y creen una idea conjunta.',
      validacion: 'Formulario de equipo o validación',
      puntos: 30,
    },
  ];
  