export const private_universities = [
  "Pontificia Universidad Católica del Perú",
  "Universidad Peruana Cayetano Heredia",
  "Universidad Católica de Santa María",
  "Universidad del Pacífico",
  "Universidad de Lima",
  "Universidad de San Martín de Porres",
  "Universidad Femenina del Sagrado Corazón",
  "Universidad Inca Garcilaso de la Vega",
  "Universidad Marcelino Champagnat",
  "Universidad de Piura",
  "Universidad Ricardo Palma",
  "Universidad Andina del Cusco",
  "Universidad Peruana Los Andes",
  "Universidad Peruana Unión",
  "Universidad Tecnológica de los Andes",
  "Universidad de Huánuco",
  "Universidad Privada de Tacna",
  "Universidad Privada Antenor Orrego",
  "Universidad Particular de Iquitos",
  "Universidad César Vallejo",
  "Universidad Privada del Norte",
  "Facultad de Teología Pontificia y Civil de Lima",
  "Universidad Peruana de Ciencias Aplicadas",
  "Universidad San Ignacio de Loyola",
  "Universidad Católica Santo Toribio de Mogrovejo",
  "Universidad Norbert Wiener",
  "Universidad Católica San Pablo",
  "Universidad Privada San Juan Bautista",
  "Universidad Tecnológica del Perú",
  "Universidad Católica Sedes Sapientiae",
  "Universidad Científica del Sur",
  "Universidad Continental",
  "Escuela de Postgrado Gerens",
  "Universidad Señor de Sipán",
  "Universidad Cátólica de Trujillo Benedicto XVI",
  "Universidad para el Desarrollo Andino",
  "Universidad Antonio Ruiz de Montoya",
  "Universidad ESAN",
  "Universidad Jaime Bausate y Meza",
  "Universidad Privada de Trujillo",
  "Universidad de Ciencias y Humanidades",
  "Universidad Autónoma de Ica",
  "Universidad Autónoma del Perú",
  "Universidad de Ciencias y Artes de América Latina",
  "Universidad La Salle",
  "Universidad Privada de Huancayo Franklin Roosevelt",
  "Universidad de Ingeniería y Tecnología",
  "Universidad María Auxiliadora",
  "Universidad Privada Peruano Alemana",
  "Escuela de Postgrado Neumann Business School",
];

export const public_universities = [
  "Universidad Nacional Mayor de San Marcos",
  "Universidad Nacional de San Cristóbal de Huamanga",
  "Universidad Nacional San Antonio Abad del Cusco",
  "Universidad Nacional de Educación Enrique Guzmán y Valle",
  "Universidad Nacional de Trujillo",
  "Universidad Nacional de San Agustín",
  "Universidad Nacional del Altiplano de Puno",
  "Universidad Nacional de Ingeniería",
  "Universidad Nacional Agraria La Molina",
  "Universidad Nacional San Luis Gonzaga",
  "Universidad Nacional del Centro del Perú",
  "Universidad Nacional Daniel Alcides Carrión",
  "Universidad Nacional Hermilio Valdizán",
  "Universidad Nacional de la Amazonía Peruana",
  "Universidad Nacional de Piura",
  "Universidad Nacional de Cajamarca",
  "Universidad Nacional Federico Villarreal",
  "Universidad Nacional Agraria de la Selva",
  "Universidad Nacional del Callao",
  "Universidad Nacional José Faustino Sánchez Carrión",
  "Universidad Nacional Pedro Ruiz Gallo",
  "Universidad Nacional Jorge Basadre Grohmann",
  "Universidad Nacional Santiago Antúnez de Mayolo",
  "Universidad Nacional de Ucayali",
  "Universidad Nacional de San Martín",
  "Universidad Nacional del Santa",
  "Universidad Nacional de Tumbes",
  "Universidad Nacional de Huancavelica",
  "Universidad Nacional Amazónica de Madre de Dios",
  "Universidad Nacional Intercultural de la Amazonía",
  "Universidad Nacional Micaela Bastidas de Apurímac",
  "Universidad Nacional Toribio Rodríguez de Mendoza de Amazonas",
  "Universidad Nacional Tecnológica de Lima Sur",
  "Universidad Nacional José María Arguedas",
  "Universidad Nacional de Moquegua",
  "Universidad Nacional de Juliaca",
  "Universidad Nacional Autónoma Altoandina de Tarma",
  "Universidad Nacional Autónoma de Chota",
  "Universidad Nacional de Frontera",
  "Universidad Nacional Intercultural de la Selva Central Juan Santos Atahualpa",
  "Universidad Nacional Intercultural Fabiola Salazar Leguía de Bagua",
  "Universidad Nacional de Barranca",
  "Universidad Nacional Autónoma de Huanta",
  "Universidad Nacional de Jaén",
  "Universidad Nacional Autónoma de Alto Amazonas",
  "Universidad Nacional Ciro Alegría",
  "Universidad Nacional Autónoma de Tayacaja Daniel Hernández Morillo",
  "Universidad Nacional de Cañete",
  "Universidad Nacional Intercultural de Quillabamba",
];
