export const private_universities = [
  { label: "Pontificia Universidad Católica del Perú", value: "Pontificia Universidad Católica del Perú" },
  { label: "Universidad Peruana Cayetano Heredia", value: "Universidad Peruana Cayetano Heredia" },
  { label: "Universidad Católica de Santa María", value: "Universidad Católica de Santa María" },
  { label: "Universidad del Pacífico", value: "Universidad del Pacífico" },
  { label: "Universidad de Lima", value: "Universidad de Lima" },
  { label: "Universidad de San Martín de Porres", value: "Universidad de San Martín de Porres" },
  { label: "Universidad Femenina del Sagrado Corazón", value: "Universidad Femenina del Sagrado Corazón" },
  { label: "Universidad Inca Garcilaso de la Vega", value: "Universidad Inca Garcilaso de la Vega" },
  { label: "Universidad Marcelino Champagnat", value: "Universidad Marcelino Champagnat" },
  { label: "Universidad de Piura", value: "Universidad de Piura" },
  { label: "Universidad Ricardo Palma", value: "Universidad Ricardo Palma" },
  { label: "Universidad Andina del Cusco", value: "Universidad Andina del Cusco" },
  { label: "Universidad Peruana Los Andes", value: "Universidad Peruana Los Andes" },
  { label: "Universidad Peruana Unión", value: "Universidad Peruana Unión" },
  { label: "Universidad Tecnológica de los Andes", value: "Universidad Tecnológica de los Andes" },
  { label: "Universidad de Huánuco", value: "Universidad de Huánuco" },
  { label: "Universidad Privada de Tacna", value: "Universidad Privada de Tacna" },
  { label: "Universidad Privada Antenor Orrego", value: "Universidad Privada Antenor Orrego" },
  { label: "Universidad Particular de Iquitos", value: "Universidad Particular de Iquitos" },
  { label: "Universidad César Vallejo", value: "Universidad César Vallejo" },
  { label: "Universidad Privada del Norte", value: "Universidad Privada del Norte" },
  { label: "Facultad de Teología Pontificia y Civil de Lima", value: "Facultad de Teología Pontificia y Civil de Lima" },
  { label: "Universidad Peruana de Ciencias Aplicadas", value: "Universidad Peruana de Ciencias Aplicadas" },
  { label: "Universidad San Ignacio de Loyola", value: "Universidad San Ignacio de Loyola" },
  { label: "Universidad Católica Santo Toribio de Mogrovejo", value: "Universidad Católica Santo Toribio de Mogrovejo" },
  { label: "Universidad Norbert Wiener", value: "Universidad Norbert Wiener" },
  { label: "Universidad Católica San Pablo", value: "Universidad Católica San Pablo" },
  { label: "Universidad Privada San Juan Bautista", value: "Universidad Privada San Juan Bautista" },
  { label: "Universidad Tecnológica del Perú", value: "Universidad Tecnológica del Perú" },
  { label: "Universidad Católica Sedes Sapientiae", value: "Universidad Católica Sedes Sapientiae" },
  { label: "Universidad Científica del Sur", value: "Universidad Científica del Sur" },
  { label: "Universidad Continental", value: "Universidad Continental" },
  { label: "Escuela de Postgrado Gerens", value: "Escuela de Postgrado Gerens" },
  { label: "Universidad Señor de Sipán", value: "Universidad Señor de Sipán" },
  { label: "Universidad Cátolica de Trujillo Benedicto XVI", value: "Universidad Cátolica de Trujillo Benedicto XVI" },
  { label: "Universidad para el Desarrollo Andino", value: "Universidad para el Desarrollo Andino" },
  { label: "Universidad Antonio Ruiz de Montoya", value: "Universidad Antonio Ruiz de Montoya" },
  { label: "Universidad ESAN", value: "Universidad ESAN" },
  { label: "Universidad Jaime Bausate y Meza", value: "Universidad Jaime Bausate y Meza" },
  { label: "Universidad Privada de Trujillo", value: "Universidad Privada de Trujillo" },
  { label: "Universidad de Ciencias y Humanidades", value: "Universidad de Ciencias y Humanidades" },
  { label: "Universidad Autónoma de Ica", value: "Universidad Autónoma de Ica" },
  { label: "Universidad Autónoma del Perú", value: "Universidad Autónoma del Perú" },
  { label: "Universidad de Ciencias y Artes de América Latina", value: "Universidad de Ciencias y Artes de América Latina" },
  { label: "Universidad La Salle", value: "Universidad La Salle" },
  { label: "Universidad Privada de Huancayo Franklin Roosevelt", value: "Universidad Privada de Huancayo Franklin Roosevelt" },
  { label: "Universidad de Ingeniería y Tecnología", value: "Universidad de Ingeniería y Tecnología" },
  { label: "Universidad María Auxiliadora", value: "Universidad María Auxiliadora" },
  { label: "Universidad Privada Peruano Alemana", value: "Universidad Privada Peruano Alemana" },
  { label: "Escuela de Postgrado Neumann Business School", value: "Escuela de Postgrado Neumann Business School" }
];
export const public_universities = [
  { label: "Universidad Nacional Mayor de San Marcos", value: "Universidad Nacional Mayor de San Marcos" },
  { label: "Universidad Nacional de San Cristóbal de Huamanga", value: "Universidad Nacional de San Cristóbal de Huamanga" },
  { label: "Universidad Nacional San Antonio Abad del Cusco", value: "Universidad Nacional San Antonio Abad del Cusco" },
  { label: "Universidad Nacional de Educación Enrique Guzmán y Valle", value: "Universidad Nacional de Educación Enrique Guzmán y Valle" },
  { label: "Universidad Nacional de Trujillo", value: "Universidad Nacional de Trujillo" },
  { label: "Universidad Nacional de San Agustín", value: "Universidad Nacional de San Agustín" },
  { label: "Universidad Nacional del Altiplano de Puno", value: "Universidad Nacional del Altiplano de Puno" },
  { label: "Universidad Nacional de Ingeniería", value: "Universidad Nacional de Ingeniería" },
  { label: "Universidad Nacional Agraria La Molina", value: "Universidad Nacional Agraria La Molina" },
  { label: "Universidad Nacional San Luis Gonzaga", value: "Universidad Nacional San Luis Gonzaga" },
  { label: "Universidad Nacional del Centro del Perú", value: "Universidad Nacional del Centro del Perú" },
  { label: "Universidad Nacional Daniel Alcides Carrión", value: "Universidad Nacional Daniel Alcides Carrión" },
  { label: "Universidad Nacional Hermilio Valdizán", value: "Universidad Nacional Hermilio Valdizán" },
  { label: "Universidad Nacional de la Amazonía Peruana", value: "Universidad Nacional de la Amazonía Peruana" },
  { label: "Universidad Nacional de Piura", value: "Universidad Nacional de Piura" },
  { label: "Universidad Nacional de Cajamarca", value: "Universidad Nacional de Cajamarca" },
  { label: "Universidad Nacional Federico Villarreal", value: "Universidad Nacional Federico Villarreal" },
  { label: "Universidad Nacional Agraria de la Selva", value: "Universidad Nacional Agraria de la Selva" },
  { label: "Universidad Nacional del Callao", value: "Universidad Nacional del Callao" },
  { label: "Universidad Nacional José Faustino Sánchez Carrión", value: "Universidad Nacional José Faustino Sánchez Carrión" },
  { label: "Universidad Nacional Pedro Ruiz Gallo", value: "Universidad Nacional Pedro Ruiz Gallo" },
  { label: "Universidad Nacional Jorge Basadre Grohmann", value: "Universidad Nacional Jorge Basadre Grohmann" },
  { label: "Universidad Nacional Santiago Antúnez de Mayolo", value: "Universidad Nacional Santiago Antúnez de Mayolo" },
  { label: "Universidad Nacional de Ucayali", value: "Universidad Nacional de Ucayali" },
  { label: "Universidad Nacional de San Martín", value: "Universidad Nacional de San Martín" },
  { label: "Universidad Nacional del Santa", value: "Universidad Nacional del Santa" },
  { label: "Universidad Nacional de Tumbes", value: "Universidad Nacional de Tumbes" },
  { label: "Universidad Nacional de Huancavelica", value: "Universidad Nacional de Huancavelica" },
  { label: "Universidad Nacional Amazónica de Madre de Dios", value: "Universidad Nacional Amazónica de Madre de Dios" },
  { label: "Universidad Nacional Intercultural de la Amazonía", value: "Universidad Nacional Intercultural de la Amazonía" },
  { label: "Universidad Nacional Micaela Bastidas de Apurímac", value: "Universidad Nacional Micaela Bastidas de Apurímac" },
  { label: "Universidad Nacional Toribio Rodríguez de Mendoza de Amazonas", value: "Universidad Nacional Toribio Rodríguez de Mendoza de Amazonas" },
  { label: "Universidad Nacional Tecnológica de Lima Sur", value: "Universidad Nacional Tecnológica de Lima Sur" },
  { label: "Universidad Nacional José María Arguedas", value: "Universidad Nacional José María Arguedas" },
  { label: "Universidad Nacional de Moquegua", value: "Universidad Nacional de Moquegua" },
  { label: "Universidad Nacional de Juliaca", value: "Universidad Nacional de Juliaca" },
  { label: "Universidad Nacional Autónoma Altoandina de Tarma", value: "Universidad Nacional Autónoma Altoandina de Tarma" },
  { label: "Universidad Nacional Autónoma de Chota", value: "Universidad Nacional Autónoma de Chota" },
  { label: "Universidad Nacional de Frontera", value: "Universidad Nacional de Frontera" },
  { label: "Universidad Nacional Intercultural de la Selva Central Juan Santos Atahualpa", value: "Universidad Nacional Intercultural de la Selva Central Juan Santos Atahualpa" },
  { label: "Universidad Nacional Intercultural Fabiola Salazar Leguía de Bagua", value: "Universidad Nacional Intercultural Fabiola Salazar Leguía de Bagua" },
  { label: "Universidad Nacional de Barranca", value: "Universidad Nacional de Barranca" },
  { label: "Universidad Nacional Autónoma de Huanta", value: "Universidad Nacional Autónoma de Huanta" },
  { label: "Universidad Nacional de Jaén", value: "Universidad Nacional de Jaén" },
  { label: "Universidad Nacional Autónoma de Alto Amazonas", value: "Universidad Nacional Autónoma de Alto Amazonas" },
  { label: "Universidad Nacional Ciro Alegría", value: "Universidad Nacional Ciro Alegría" },
  { label: "Universidad Nacional Autónoma de Tayacaja Daniel Hernández Morillo", value: "Universidad Nacional Autónoma de Tayacaja Daniel Hernández Morillo" },
  { label: "Universidad Nacional de Cañete", value: "Universidad Nacional de Cañete" },
  { label: "Universidad Nacional Intercultural de Quillabamba", value: "Universidad Nacional Intercultural de Quillabamba" }
];